#!/bin/sh  
f=$1  
shift  
cmd=$*  
tmpf="`mktemp /tmp/onchange.XXXXX`"  
cp "$f" "$tmpf"  
trap "rm $tmpf; exit 1" 2  
make
if [ $? -eq 0 ]; then
  ./${f%%.*}
fi
while : ; do  
  if [ "$f" -nt "$tmpf" ]; then  
    cp "$f" "$tmpf" 
    make
    if [ $? -eq 0 ]; then
      ./${f%%.*}
    fi
  fi  
  sleep 2  
done  
